#!/usr/bin/env bash
#
# setup-software.sh  —  Module 7: Software, Packages, and Archives
#
# Builds the lab scenario inside your Multipass VM. Run it ONCE with sudo:
#     sudo bash setup-software.sh
#
# It creates a small "project" directory full of files for you to archive
# later in the lab, and leaves a starter copy of the evidence report in your
# home directory. It does NOT install or remove any packages — that part of
# the lab is yours to do by hand so you practice the package manager.
#
# This script is safe and idempotent: re-running it rebuilds the project
# directory from scratch and does not touch system packages or services.
#
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Please run with sudo:  sudo bash setup-software.sh"
  exit 1
fi

# Work out the human's home directory even though we're running as root via sudo.
TARGET_USER="${SUDO_USER:-ubuntu}"
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
TARGET_HOME="${TARGET_HOME:-/home/ubuntu}"

PROJECT="${TARGET_HOME}/projectfiles"

echo "[setup] Building a sample project directory at ${PROJECT} ..."
# Idempotent: clear any prior state so a re-run starts clean.
rm -rf "$PROJECT"
mkdir -p "$PROJECT/docs" "$PROJECT/logs"

# Seed it with several text files of meaningful size, so that compressing the
# archive visibly shrinks it (highly repetitive text compresses well — this is
# the point students will observe when they compare sizes).
{
  echo "# Quarterly Project Notes"
  echo "Generated by the Module 7 lab setup script."
  echo
} > "$PROJECT/docs/README.txt"

# A repetitive log file that will compress dramatically.
for i in $(seq 1 2000); do
  echo "2026-05-23 INFO  service heartbeat ok  seq=${i}  status=NOMINAL"
done > "$PROJECT/logs/service.log"

# A second data file with some variety.
for i in $(seq 1 500); do
  echo "record,${i},$(printf 'value-%04d' "$i"),active"
done > "$PROJECT/docs/data.csv"

echo "hello from the project" > "$PROJECT/docs/note.txt"

# Make sure the human owns everything (we created it as root).
chown -R "${TARGET_USER}:${TARGET_USER}" "$PROJECT"

# Drop a starter evidence report so students know the expected filename and
# the headings the check will look for. They overwrite/append real output.
REPORT="${TARGET_HOME}/module7-software-report.txt"
if [[ ! -f "$REPORT" ]]; then
  cat > "$REPORT" <<EOF
MODULE 7 EVIDENCE REPORT — Software, Packages, and Archives
(Replace these placeholders with the real command output from your VM.)

Hostname:
(paste the output of:  hostname)

=== APT / PACKAGE EVIDENCE ===
(paste the relevant output of:  apt show <pkg> , dpkg -l | grep <pkg> , dpkg -L <pkg>)

=== ARCHIVE EVIDENCE ===
(paste the output of:  tar -tzf ~/backup.tar.gz   and the size comparison)
EOF
  chown "${TARGET_USER}:${TARGET_USER}" "$REPORT"
fi

echo
echo "[setup] Done."
echo "        - Sample project to archive:   ${PROJECT}"
echo "        - Starter evidence report:     ${REPORT}"
echo "        Follow the lab instructions, then grade yourself with:"
echo "            bash check-software.sh"
